### ISSUE TITLE
Not compatible with GridLayout

### ISSUE THREAD

**Issue by saugs** [rcketscientist/ToggleButtons#10]
Hi, thanks for your library !

I just have a problem building an app with GridLayout, that causes the following error :
`.gradle\caches\transforms-1\files-1.1\gridlayout-1.0.0.aar\f8560c035b06149b18ef9b4c9a49e4a2\res\values\values.xml:74:5-190:25: AAPT: error: duplicate value for resource 'attr/orientation' with config ''`

**Comment by rcketscientist** [comment]
Do you have example source...this error only exists with toggle buttons?

**Comment by saugs** [comment]
It happens on gradle sync just after adding the ToggleButtons dependency, even on a clean project with GridLayout, so there is no source code evolved.
The sync just fails with the mentioned error

**Comment by rcketscientist** [comment]
That is not all that's required to reproduce.  I can run a Toggle(Button/Group) in a GridLayout just fine.  You'll need to link a project demonstrating this.
