### ISSUE TITLE
Compilation fail with latest material components

### ISSUE THREAD

**Issue by dioKaratzas** [rcketscientist/ToggleButtons#13]
The Android resource compilation fail with the latest version of material components.
Version ```'com.google.android.material:material:1.1.0-alpha07'```

The output:
```
Android resource compilation failed
app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:8308: error: duplicate value for resource 'attr/checkedButton' with config ''.
app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:8308: error: resource previously defined here.
app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml: error: file failed to compile.
```

**Comment by rcketscientist** [comment]
Looks like Google finally released their own version:

`MaterialButtonToggleGroup`

I recommend using their version, unless you find a deficiency.  Since this was always a stop-gap, I'll note it in the readme and point folks to the official option.

If you find a deficiency, let me know and I'll re-open.

**Comment by dioKaratzas** [comment]
I think that the ```MaterialButtonToggleGroup``` does not support vertical orientation.

**Comment by rcketscientist** [comment]
It's also missing exclusive and unselect control.

I welcome a PR.  Likely just need to deconflict the styling names. Im in
the middle of a move and won't be able to look for a week or two.

**Comment by dioKaratzas** [comment]
I will wait for this update because i can't update to the latest ```MaterialComponents``` version. Thank you!

**Comment by dioKaratzas** [comment]
Can you re-open the issue? Its an open issue!

**Comment by rcketscientist** [comment]
As I mentioned it's a bad month for me, opening the issue won't fix it.  I'll need a PR or you'll have to wait until after my move.

**Comment by BenjyTec** [comment]
I just left a pull request - please tell me kindly if it is useful, as I am quite new in coding and GitHub (and this is my first created PR)... 
I checked out MaterialButtonToggleGroup from Google, but I will stick to your library, as it allows comfortable weighting of the Buttons, while Google doesn't. Thanks for you efforts!

**Comment by BenjyTec** [comment]
Great, with 4.0.0 it's working. Thanks for your efforts! This issue can be closed.
