### ISSUE TITLE
Compatibility issue

### ISSUE THREAD

**Issue by viestursGr** [rcketscientist/ToggleButtons#4]
Error:Execution failed for task ':app:processDevDebugManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 16 cannot be smaller than version 21 declared in library [com.anthonymandra:ToggleButtons:1.1.0] C:\Users\dev\.android\build-cache\e4ed249ed1082d551294b9aaf166e3d2c15e2103\output\AndroidManifest.xml
	Suggestion: use tools:overrideLibrary="com.anthonymandra.widget" to force usage

Can you make a version that would reasonably work on min 16?

**Comment by rcketscientist** [comment]
Yes, take a look at `cardview`. It demonstrates the back compat needed to
support to 11 or 12. I don't have the time atm, but a pr would be welcome.

**Comment by rcketscientist** [comment]
Backwards compatibility to API 9 in the `backCompat` tree, commit 4b493a0c900849cfb00cabab95ca20b583e5888d.  It seems to break dividers on all versions so some testing and tweaks will be needed.

**Comment by rcketscientist** [comment]
Compatibility to API 9 is now in master and repository.

`compile 'com.anthonymandra:ToggleButtons:2.0.0'`

**Comment by abunayem** [comment]
Not supporting the latest Appcompat version. the latest version is 7.26+. and you are using 7.25

**Comment by rcketscientist** [comment]
Is there an incompatibility?

**Comment by abunayem** [comment]
yes. when I add this lib in app's dependencies. showing this error:
Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute meta-data#android.support.VERSION@value value=(26.0.0-alpha1) from [com.android.support:design:26.0.0-alpha1] AndroidManifest.xml:27:9-38
	is also present at [com.android.support:cardview-v7:25.3.1] AndroidManifest.xml:24:9-31 value=(25.3.1).
	Suggestion: add 'tools:replace="android:value"' to <meta-data> element at AndroidManifest.xml:25:5-27:41 to override.
