### ISSUE TITLE
Crashing on 4.x devices using Vector Drawables

### ISSUE THREAD

**Issue by KennyGoers** [rcketscientist/ToggleButtons#6]
Using ToggleButton with an XML drawable on 4.X devices I'm unable to inflate the layout. I use the "android:button" element to specify the drawable, is there a compat attribute to use instead?
```

Caused by android.content.res.Resources$NotFoundException: File res/drawable/ic_all_24dp.xml from drawable resource ID #0x7f020138
       at android.content.res.Resources.loadDrawable(Resources.java:2206)
       at android.content.res.TypedArray.getDrawable(TypedArray.java:602)
       at android.widget.CompoundButton.<init>(CompoundButton.java:74)
```

(BTW, love the simplicity of the library!)

**Comment by rcketscientist** [comment]
Hmm, at first glance that looks like you're missing the resource you'd like to use on the button itself (ic_all_24dp).

**Comment by KennyGoers** [comment]
I think that's how it appears when it isn't looking for or can't see vector
resources, works perfectly well on all other devices. I'll do some more
debugging on it, have you tested on 4.x devices with vector drawables?

**Comment by rcketscientist** [comment]
I have not specifically.  But what's done with the icons themselves is not unique to the library.

Also note:

_Android 4.4 (API level 20) and lower doesn't support vector drawables. If your minimum API level is set at one of these API levels, you have two options when using Vector Asset Studio: generate Portable Network Graphic (PNG) files (the default) or use the Support Library._

**Comment by KennyGoers** [comment]
It's particular to using "vectorDrawables.useSupportLibrary = true" in your gradle file with the app, if you add this to the sample app if crashes in the same way i showed above. For my apps I use vector drawables packaged in the app, the default behavior is to convert them to bitmaps of all sizes if you don't specify this to keep them as vectors and use the support library.  I'll see if I can change it somehow, the base CompoundButton (base constructor) doesn't handle loading android:button images from vectors, so I'll fork and send you a pull request, likely it would be to add a "app:buttonCompat" attribute and load separately. Thoughts?

**Comment by rcketscientist** [comment]
This isn't something that crossed my mind.  My gut says that the support library should be managing this and that this library should be agnostic of all that.  However, this library lives a little deeper than usual, so there could be a conflict.  Let me know what you can find and I'll take a look as well this evening.  If you figure it out, PRs are welcome.

**Comment by KennyGoers** [comment]
I've figured it out, the constructor for the CompoundButton does not like the button attribute to be a vector in older versions (pre-5) and just like the support library I had to add a special attribute (see srcCompat in ImageView), AppCompat did for the most part add overrides but not for CompoundButton. I got it working locally and will try to put a Pull Request to you.

**Comment by KennyGoers** [comment]
Was going to update in the development branch and noticed my update could be simpler. I'll change that in the pull request I do for development. Also, you want to be the target as 25?

**Comment by rcketscientist** [comment]
I'm fine with the latest as long as it doesn't raise the min.  Was it 26 that deprecated <14?

**Comment by rcketscientist** [comment]
Did you get a chance to swap the PR to develop?

**Comment by rcketscientist** [comment]
Feel free to repost the PR if still relevant
