### ISSUE TITLE
how to add vector drawable left or right with text

### ISSUE THREAD

**Issue by iweey** [rcketscientist/ToggleButtons#8]
how to add vector drawable left or right with text

now just icon.
i want to add icon left or right with text.
how to do ?
thanks

**Comment by rcketscientist** [comment]
Have you attempted to use the left or right drawables?  The buttons are `CompoundButton` at their core, so it should be possible. https://github.com/rcketscientist/ToggleButtons/blob/d1a5baf350b60459b00d46f63397545052e5d083/library/src/main/java/android/support/v7/widget/ToggleButton.java#L58

Make sure you have text and it should behave just like a typical button.
